### ISSUE TITLE
system filtering doesn't offer 'creator'

### ISSUE THREAD

**Issue by BloodyRain2k** [gregmalcolm/ed-materializer#17]
As listed on https://github.com/gregmalcolm/ed-materializer/wiki/Schema---V4---Systems is the only player related filter _updater_, which is the person who made the last update, but it's not neccessarly the one that created the entry.

I'm currently working on a Win32 client and while it can barely do anything yet can it atleast patch coordinates in which it fetches from my netlogs.
And the reason why I'd prefer to be able to filter by either _creator_ or _updaters_ is 'damage' control.

I know that we can update pretty much all entries but for safety reasons am I limiting it to entries I made, or I would atleast.
Technically can I only limit it to entries I updated last, which is close but not the same.

**Comment by gregmalcolm** [comment]
Hmm, that would be pretty easy to do. I might have a moment tonight to look into it. And maybe that search filter thing while I'm at it

**Comment by gregmalcolm** [comment]
Deploying it now

**Comment by BloodyRain2k** [comment]
_creator_ works :D
_updaters_ not yet though :o

While on the filtering anyways: any thoughts about being able to query for multiple systems at once by name? something like &systems=["deciat","bd+22 3878"] ?
