### ISSUE TITLE
Force updaters to send an updater/commander param

### ISSUE THREAD

**Issue by gregmalcolm** [gregmalcolm/ed-materializer#3]
When applications like EDDiscovery make PATCH updates it will be necessary to include the updater or commander param filled out with the actual commander name. In some cases like Site Survey the change will be rejected if the commander name sent doesn't match the record owner.

**Comment by gregmalcolm** [comment]
This one will affect you @finwen

**Comment by finwen** [comment]
OK :) Should be easy to fix

2016-03-09 3:14 GMT+01:00 Greg Malcolm <notifications@github.com>:
