### ISSUE TITLE
Monster sheet import  wrong radius on many planets.

### ISSUE THREAD

**Issue by finwen** [gregmalcolm/ed-materializer#8]
For example Achenar 3

"mass": 41.12
"radius": 15

in monster sheet.   radius is  15,763  and mass is  41.1200

, is thousend delimiter so it should be 15763---

**Comment by gregmalcolm** [comment]
Ah, it'll be treating the comma as end of number. Silly Ruby. :)

**Comment by gregmalcolm** [comment]
Fixed:
http://ed-materializer-env.elasticbeanstalk.com/api/v2/worlds?system=achenar

The fix will affect all large number fields.

I also tweaked the importer so it will only update records if the updater is "DW Spreadsheet". That way if a user changes something outside the spreadsheet it won't get changed back.

**Comment by finwen** [comment]
Seems to work fine now. :)

2016-03-05 1:03 GMT+01:00 Greg Malcolm <notifications@github.com>:
