### ISSUE TITLE
Daily Data Dumps

### ISSUE THREAD

**Issue by gregmalcolm** [gregmalcolm/ed-materializer#9]
Presumably each time a new EDDiscovery starts prospecting they are going to need to download all the prospector data. Rather pull it all down via the API it would probably be more efficient to just download zipped json files to get things started.

I'm thinking one .json.zip per API interface. 

Eg:

`ed-materializer-env.elasticbeanstalk.com/downloads/v2/stars.json.zip`
`ed-materializer-env.elasticbeanstalk.com/downloads/v2/worlds.json.zip`

The json data will be in the same format as the api GET INDEX format. More or less.

**Comment by gregmalcolm** [comment]
Note: I can't really automate the daily zip file generation on the heroku test site. I suggest for downloading just pull from the prod (amazon) site when the feature is online.

**Comment by finwen** [comment]
404 Not found then i tried the links now

2016-03-14 17:09 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by gregmalcolm** [comment]
Yeah, still figuring out the heroku/aws deployment part. But works on my machine (tm). :)

**Comment by gregmalcolm** [comment]
Ok, I changed things around a bit. Now the zip files are regenerated dynamically as they are requested when the data gets too old (when the file hasn't been generated yet on a given day). I still plan to sort out a scheduled update routine for that, but it's harder to do than you would think in cloud services. Also it's possible that if you hit different servers within a cluster you may end up with slightly different results as the files are generating per server at whatever time they are requested.

On the plus side even the Heroku version is self updating using this strategy.

Documentation:

https://github.com/gregmalcolm/ed-materializer/wiki/Schema---Daily-Data-Dumps
